# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_course_arrangement?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # Druid连接池配置
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 5
      max-wait: 3000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: false
      test-on-return: false
      fail-fast: true
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 热部署配置
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

  #设置文件传输大小限制
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis-plus:
  mapper-locations: classpath:/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.lyk.coursearrange.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 #删除
      logic-not-delete-value: 0 #不删除

server:
  port: 8008


# 阿里云OSS
aliyun:
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 你们自己的key
      accessKeySecret: 你们自己的密钥
      bucketName: arrange